[transport-udp]
type = transport
protocol = udp
bind = 0.0.0.0:5060

[1001]
type = endpoint
context = internal
disallow = all
allow = ulaw,alaw
auth = 1001
aors = 1001

[1001]
type = auth
auth_type = userpass
password = 1001pass
username = 1001

[1001]
type = aor
max_contacts = 1

[1002]
type = endpoint
context = internal
disallow = all
allow = ulaw,alaw
auth = 1002
aors = 1002

[1002]
type = auth
auth_type = userpass
password = 1002pass
username = 1002

[1002]
type = aor
max_contacts = 1
