[transport-udp]
type = transport
protocol = udp
bind = 0.0.0.0:5060

[1001]
type = endpoint
context = internal
disallow = all
allow = ulaw,alaw
auth = 1001
aors = 1001
force_rport = yes
rewrite_contact = yes
rtp_symmetric = yes
direct_media = no

[1001]
type = auth
auth_type = userpass
password = __SIP_PASSWORD_1001_RUNTIME__
username = 1001

[1001]
type = aor
max_contacts = 1

[1002]
type = endpoint
context = internal
disallow = all
allow = ulaw,alaw
auth = 1002
aors = 1002
force_rport = yes
rewrite_contact = yes
rtp_symmetric = yes
direct_media = no

[1002]
type = auth
auth_type = userpass
password = __SIP_PASSWORD_1002_RUNTIME__
username = 1002

[1002]
type = aor
max_contacts = 1
